#!/bin/bash

# 🚀 Production Migration Script
# Generated by Day 31 Production Preparation

set -e

echo "🚀 Starting production migration..."

# 1. Backup current database
echo "📦 Creating database backup..."
cp prisma/dev.db "backups/production/backup-$(date +%Y%m%d_%H%M%S).db" || echo "⚠️ Backup failed, continuing..."

# 2. Generate Prisma client
echo "🔧 Generating Prisma client..."
npx prisma generate

# 3. Run database migrations
echo "🗄️ Running database migrations..."
npx prisma migrate deploy

# 4. Verify migration
echo "✅ Verifying migration..."
npx prisma db pull --print

echo "🎉 Production migration completed successfully!"
